Controllers/SelectController.cs
using ClosedXML.Excel;
using DBConTemplate.Models;
using MySql.Data.MySqlClient;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DBConTemplate.Controllers
{
    public class SelectController : Controller
    {
        //ログ
        protected static NLog.Logger log = NLog.LogManager.GetLogger("log");

        //リストページ
        public ActionResult AjaxSelect()
        {
            SelectModel selectModel = new SelectModel();
            String errorMessage = String.Empty;
            try
            {
                selectModel.GetStatus();
                selectModel.GetUser();
            }
            catch
            {

            }
            return View(selectModel);
        }

        //全件取得
        public ActionResult GetDataFromAjax(int count)
        {
            SelectModel selectModel = new SelectModel();
            String errorMessage = String.Empty;
            try
            {
                //データ取得
                selectModel.GetData(count);
            }
            catch (Exception e)
            {
                log.Fatal(e);
                errorMessage = "データの取得に失敗しました。";
            }
            return Json(new { DATA = selectModel, ErrorMessage = errorMessage });
        }

        //降順切り替え
        public ActionResult DataSortDesc(int count)
        {
            SelectModel selectModel = new SelectModel();
            String errorMessage = String.Empty;
            try
            {
                //データ取得
                selectModel.GetDataDesc(count);
            }
            catch (Exception e)
            {
                log.Fatal(e);
                errorMessage = "データの取得に失敗しました。";
            }
            return Json(new { DATA = selectModel, ErrorMessage = errorMessage });
        }

        //昇順切り替え
        public ActionResult DataSortAsc(int count)
        {
            SelectModel selectModel = new SelectModel();
            String errorMessage = String.Empty;
            try
            {
                //データ取得
                selectModel.GetDataAsc(count);
            }
            catch (Exception e)
            {
                log.Fatal(e);
                errorMessage = "データの取得に失敗しました。";
            }
            return Json(new { DATA = selectModel, ErrorMessage = errorMessage });
        }

        //検索
        public ActionResult SearchData(string statusSearch, string chargeSearch, int count)
        {
            SelectModel selectModel = new SelectModel();
            String errorMessage = String.Empty;
            try
            {
                //データ取得
                selectModel.GetSearchData(statusSearch, chargeSearch, count);
            }
            catch (Exception e)
            {
                log.Fatal(e);
                errorMessage = "データの取得に失敗しました。";
            }
            return Json(new { DATA = selectModel, ErrorMessage = errorMessage });
        }

        //データ削除
        public ActionResult DeleteData(string cd)
        {
            SelectModel selectModel = new SelectModel();
            String errorMessage = String.Empty;
            try
            {
                selectModel.DelData(cd);
            }
            catch (Exception e)
            {
                log.Fatal(e);
                errorMessage = "データの削除に失敗しました。";
            }
            return Json(new { DATA = selectModel, ErrorMessage = errorMessage });
        }

        //新規作成画面
        public ActionResult CreateData()
        {
            SelectModel selectModel = new SelectModel();
            String errorMessage = String.Empty;
            try
            {
                selectModel.GetStatus();
                selectModel.GetUser();
            }
            catch (Exception e)
            {
                log.Fatal(e);
            }
            return View(selectModel);
        }

        //新規作成
        public ActionResult SubmitNewData(string companyName, string companyUrl, string status, string charge, string note)
        {
            SelectModel selectModel = new SelectModel();
            String errorMessage = String.Empty;
            try
            {
                if (charge == "")
                {
                    charge = "0";
                }
                selectModel.CreateNewData(companyName, companyUrl, status, charge, note);
                if (selectModel.errorFlg != 0)
                {
                    errorMessage = "データの作成に失敗しました。";
                }
            }
            catch (Exception e)
            {
                log.Fatal(e);
                errorMessage = "データの削除に失敗しました。";
            }
            return Json(new { DATA = selectModel, ErrorMessage = errorMessage });
        }

        //データ編集画面
        public ActionResult EditData(string dataCd)
        {
            var SelectModel = new SelectModel();
            try
            {
                SelectModel = SelectModel.GetOneData(dataCd);
                SelectModel = SelectModel.GetStatus();
                SelectModel = SelectModel.GetUser();
            }
            catch (Exception e)
            {
                log.Fatal(e);
            }
            return View("EditData", SelectModel);
        }

        //データ更新
        public ActionResult EditDataSubmit(string cd, string companyName, string companyUrl, string status, string charge, string note)
        {
            SelectModel selectModel = new SelectModel();
            String errorMessage = String.Empty;
            try
            {
                //データ取得
                selectModel.EditData(cd, companyName, companyUrl, status, charge, note);
            }
            catch (Exception e)
            {
                log.Fatal(e);
                errorMessage = "データの削除に失敗しました。";
            }
            return Json(new { DATA = selectModel, ErrorMessage = errorMessage });
        }

        //EXCEL出力
        public void DownloadExcel()
        {
            SelectModel selectModel = new SelectModel();
            selectModel.GetAllData();
            using (var stream = new MemoryStream())
            {
                // Excel ファイル作成
                var workbook = new XLWorkbook();
                //シート作成
                var worksheet = workbook.Worksheets.Add("営業先リスト");
                //ヘッダー書き込み
                worksheet.Cell("A1").Value = "企業名";
                worksheet.Cell("B1").Value = "URL";
                worksheet.Cell("C1").Value = "担当者";
                worksheet.Cell("D1").Value = "状態";
                worksheet.Cell("E1").Value = "備考";
                worksheet.Cell("F1").Value = "更新日";
                //スタイル設定
                worksheet.Range("A1:F1").Style.Border.BottomBorder = XLBorderStyleValues.Double;
                worksheet.Range("A1:F1").Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;

                //データ書き込み
                for (int i = 0; i < selectModel.listData.Count; i++)
                {
                    var color = XLColor.Yellow;
                    var number = i + 2;
                    worksheet.Cell("A" + number).SetValue(selectModel.listData[i].companyName).Style.Alignment.SetHorizontal(XLAlignmentHorizontalValues.Left);
                    worksheet.Cell("B" + number).SetValue(selectModel.listData[i].companyUrl).Style.Alignment.SetHorizontal(XLAlignmentHorizontalValues.Left);
                    worksheet.Cell("C" + number).SetValue(selectModel.listData[i].charge).Style.Alignment.SetHorizontal(XLAlignmentHorizontalValues.Left);
                    worksheet.Cell("D" + number).SetValue(selectModel.listData[i].status).Style.Alignment.SetHorizontal(XLAlignmentHorizontalValues.Left);
                    worksheet.Cell("E" + number).SetValue(selectModel.listData[i].note).Style.Alignment.SetHorizontal(XLAlignmentHorizontalValues.Left);
                    worksheet.Cell("F" + number).SetValue(selectModel.listData[i].date).Style.Alignment.SetHorizontal(XLAlignmentHorizontalValues.Left);

                    if(selectModel.listData[i].charge == "未定")
                    {
                        worksheet.Cell("A" + number).Style.Fill.SetBackgroundColor(color);
                        worksheet.Cell("B" + number).Style.Fill.SetBackgroundColor(color);
                        worksheet.Cell("C" + number).Style.Fill.SetBackgroundColor(color);
                        worksheet.Cell("D" + number).Style.Fill.SetBackgroundColor(color);
                        worksheet.Cell("E" + number).Style.Fill.SetBackgroundColor(color);
                        worksheet.Cell("F" + number).Style.Fill.SetBackgroundColor(color);
                    }
                }

                // 列の幅を自動調整する
                worksheet.Column("A").AdjustToContents();
                worksheet.Column("B").AdjustToContents();
                worksheet.Column("C").AdjustToContents();
                worksheet.Column("D").AdjustToContents();
                worksheet.Column("E").AdjustToContents();
                worksheet.Column("F").AdjustToContents();

                //ブック保存
                workbook.SaveAs(stream);

                // ダウンロード
                var date = DateTime.Now.ToString("MMdd");
                var fileName = "SalesList" + date;
                Response.Clear();
                Response.Buffer = true;
                Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                Response.AddHeader("Content-Length", stream.Length.ToString());
                Response.AddHeader("Content-Disposition", $"attachment; filename={fileName}.xlsx");
                Response.BinaryWrite(stream.ToArray());
                Response.Flush();
                Response.End();
            }
        }

        //データ編集画面
        public ActionResult AggrGate()
        {
            var SelectModel = new SelectModel();
            try
            {
                //棒グラフ生成データ取得

Views/Select/AggrGate.cshtml
@model DBConTemplate.Models.SelectModel
@{
    var maxcnt = 0;
    var barKeyList = new List<string>();
}
@section scripts{
    @Scripts.Render("~/Scripts/Chart.js")
    <script type="text/javascript">
        $(function () {
            var auth = sessionStorage.getItem("auth");
            if (auth != 1) {
                window.location.href = "../Login/Login";
            }
            @if (Model.dataCount > 15)
            {
                maxcnt = 15;
            }
            else if (Model.dataCount > 30)
            {
                maxcnt = 30;
            }
            else if (Model.dataCount > 50)
            {
                maxcnt = 50;
            }
            makeBarChart();
            makePieChart();
        });

        function makeBarChart() {
            var ctx = $("#myBarChart");
            var myBarChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: [@foreach (var Item in Model.barChartDic.Select((x, i) => new { Index = i, Value = x }))
                                    {
                                        if(Item.Index == Model.barChartDic.Count() - 1)
                                        {
                                            <text>
                                            '@Item.Value.Key'
                                            </text>
                                        }
                                        else
                                        {
                                            <text>
                                            '@Item.Value.Key',
                                            </text>
                                        }
                                }],
                    datasets: [
                        {
                        label: 'ステータス別集計',
                            data:[@foreach (var Item in Model.barChartDic.Select((x, i) => new { Index = i, Value = x }))
                                    {
                                        if(Item.Index == Model.barChartDic.Count() - 1)
                                        {
                                            <text>
                                            '@Item.Value.Value'
                                            </text>
                                        }
                                        else
                                        {
                                            <text>
                                            '@Item.Value.Value',
                                            </text>
                                        }
                                }],
                            backgroundColor: "#485696"
                        }
                    ]
                },
                options: {
                    title: {
                        display: true,
                        text: 'ステータス別件数'
                    },
                    scales: {
                        yAxes: [{
                            ticks: {
                                suggestedMax: @maxcnt,
                                suggestedMin: 0,
                                stepSize: 1,
                                callback: function (value, index, values) {
                                    return value + '件'
                                }
                                }
                        }]
                    },
                }
            });
        }

    function makePieChart() {
        var colors = [];
            var ctx = document.getElementById("myPieChart");
            var colorCnt = @Model.pieChartDic.Count;
            for (var i = 0; i <colorCnt; i++) {
                var randomColor = "rgb(" + (~~(256 * Math.random())) + ", " + (~~(256 * Math.random())) + ", " + (~~(256 * Math.random())) + ")";
                colors.push(randomColor);
            }
                var myPieChart = new Chart(ctx, {
                type: 'pie',
                data: {
                    labels: [@foreach (var Item in Model.pieChartDic.Select((x, i) => new { Index = i, Value = x }))
                                    {
                                        if(Item.Index == Model.pieChartDic.Count() - 1)
                                        {
                                            <text>
                                            '@Item.Value.Key'
                                            </text>
                                        }
                                        else
                                        {
                                            <text>
                                            '@Item.Value.Key',
                                            </text>
                                        }
                                }],
                    datasets: [{
                        backgroundColor: colors,
                        data: [@foreach (var Item in Model.pieChartDic.Select((x, i) => new { Index = i, Value = x }))
                                    {
                                        if(Item.Index == Model.pieChartDic.Count() - 1)
                                        {
                                            <text>
                                            '@Item.Value.Value'
                                            </text>
                                        }
                                        else
                                        {
                                            <text>
                                            '@Item.Value.Value',
                                            </text>
                                        }
                                }]
                    }]
                },
                options: {
                    title: {
                        display: true,
                        text: '担当件数'
                    }
                }
            });
        }
    </script>
}

<h2>データ集計</h2>

<div class="jumbotron">
    <div class="col-12">
        <canvas id="myBarChart" style="position:relative; height:70vh; width:80vw"></canvas>
    </div>
</div>

<div class="jumbotron">
    <div class="row">
        <div class="col-9 text-left">
            <canvas id="myPieChart" style="position:relative; height:70vh; width:80vw"></canvas>
        </div>
        <ul class="col-3 text-left" id="pieChartNo">
            @foreach (var Item in Model.pieChartDic.Select((x, i) => new { Index = i, Value = x }))
            {
                if (Item.Index == Model.pieChartDic.Count() - 1)
                {
                    <li class="col-12 text-left">
                        <h4>@Item.Value.Key : @Item.Value.Value 件</h4>
                    </li>
                }
                else
                {
                    <li class="col-12 text-left mb-3">
                        <h4>@Item.Value.Key : @Item.Value.Value 件</h4>
                    </li>
                }
            }
        </ul>
    </div>
</div>

Views/Select/AjaxSelect.cshtml
@model DBConTemplate.Models.SelectModel
@section scripts{
    @Scripts.Render("~/Scripts/DBConTemplate/AjaxSelect.js")
    <script type="text/javascript">
        $(function () {
            var auth = sessionStorage.getItem("auth");
            if (auth != 1) {
                window.location.href = "../Login/Login";
            }
            getData(0);
        });

        function editData(cd) {
            $('#dataCd').val(cd);
            $('#toEditData').submit();
        }

        function excelDownload() {
            $('#toExcel').submit();
        }
    </script>
}

<div class="form-row">
    <div class="form-group col-2">
        <select id="statusSearch" class="form-control">
            <option value='' selected>状態</option>
            @for (var i = 0; i < Model.statusList.Count; i++)
            {
                if (Model.statusList[i].cd != "0")
                {
                    <option value="@Model.statusList[i].cd">@Model.statusList[i].status</option>
                }
            }
        </select>
    </div>
    <div class="form-group col-3">
        <select id="chargeSearch" class="form-control">
            <option value="" selected>担当者</option>
            @for (var i = 0; i < Model.userList.Count; i++)
            {
                <option value="@Model.userList[i].cd">@Model.userList[i].userName</option>
            }
        </select>
    </div>
    <div class="form-group col-1">
        <button type="button" class="btn btn-primary" onclick="searchCheck()">検索</button>
    </div>
    <div class="col-2 text-left">
        <button type="button" class="btn btn-primary " onclick="searchDataDesc(0)">↓ 降順</button>
        <button type="button" class="btn btn-primary" onclick="getData(0)">昇順 ↑</button>
    </div>
    <div class="form-group col-3 text-right">
        <button type="button" class="btn btn-info" onclick="createData()">新規作成</button>
    </div>
</div>

<h4 id="totalCount"></h4>

<table class="table">
    <thead class=" thead-dark text-center">
        <tr>
            <th scope="col">企業名</th>
            <th scope="col">メールアドレス</th>
            <th scope="col">状態</th>
            <th scope="col">担当者</th>
            <th scope="col">備考</th>
            <th scope="col">更新日</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody class="text-center" id="dataList">
    </tbody>
</table>

<div class="text-center">
    <button type="button" class="btn btn-primary" onclick="excelDownload()">Excel出力</button>
</div>

<div class="pager" id="paging"></div>

@using (Html.BeginForm("EditData", "Select", FormMethod.Post, new { @id = "toEditData" }))
{
    @Html.Hidden("dataCd", new { @id = "dataCd" })
}

@using (Html.BeginForm("DownloadExcel", "Select", FormMethod.Post, new { @id = "toExcel" }))
{
    @Html.Hidden("dataCd", new { @id = "dataCd" })
}

Views/Select/CreateUser.cshtml
@model DBConTemplate.Models.SelectModel
@section scripts{
    @Scripts.Render("~/Scripts/DBConTemplate/CreateUser.js")

    <script type="text/javascript">
        $(function () {
            var auth = sessionStorage.getItem("auth");
            if (auth != 1) {
                window.location.href = "../Login/Login";
            }
        });

        function toList() {
            window.location.href = "../Select/EditUserList";
        }
    </script>
}

<h2>ユーザー新規作成</h2>

<table class="table">
    <thead class=" thead-dark text-center">
        <tr>
            <th scope="col">名前</th>
            <th scope="col">メールアドレス</th>
            <th scope="col">パスワード</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><input type="text" id="userName" class="form-control"></td>
            <td><input type="text" id="mail" class="form-control"></td>
            <td><input type="text" id="password" class="form-control"></td>
        </tr>
    </tbody>
</table>

<div class="text-center">
    <button type="button" class="btn btn-primary" onclick="toList()">戻る</button>
    <button type="button" class="btn btn-primary" id="submit" onclick="submitData()">登録</button>
</div>

Views/Select/EditStatus.cshtml
@model DBConTemplate.Models.SelectModel
@section scripts{
    @Scripts.Render("~/Scripts/DBConTemplate/EditStatus.js")

    <script type="text/javascript">
        $(function () {
            var auth = sessionStorage.getItem("auth");
            if (auth != 1) {
                window.location.href = "../Login/Login";
            }
        });
    </script>
}

<h2>ステータス編集</h2>

<table class="table">
    <thead class="thead-dark text-center">
        <tr>
            <th scope="col">状態名称</th>
        </tr>
    </thead>
    <tbody class="text-center">
        <tr>
            <td><input type="text" id="statusName" class="form-control" value="@Model.status"></td>
        </tr>
    </tbody>
</table>

<div class="text-center">
    <button type="button" class="btn btn-primary" onclick="toList()">戻る</button>
    <button type="button" class="btn btn-primary" id="submit" onclick="submitData(@Model.cd)">登録</button>
</div>

Views/Select/EditStatusList.cshtml
@model DBConTemplate.Models.SelectModel
@section scripts{
    <script type="text/javascript">
        $(function () {
            var auth = sessionStorage.getItem("auth");
            if (auth != 1) {
                window.location.href = "../Login/Login";
            }
        });

        function editData(cd) {
            $('#statusCd').val(cd);
            $('#toEditStatus').submit();
        }

        function createData() {
            $('#toCreateStatus').submit();
        }

        function toList() {
            window.location.href = "../Select/MasterAdmin";
        }

        //データ削除処理
        function delData(cd) {
            if (!confirm("データを削除してよろしいですか？")) {
                return false;

            } else {
                $.ajax({
                    type: "POST",
                    url: "../Select/DeleteStatusSubmit",
                    data: { cd: cd },
                    beforeSend: function () {
                        showLoader();
                    }

                }).fail(function () {
                    alert("データの取得に失敗しました。")

                }).done(function (resultData) {
                    if (resultData.ErrorMessage != null && resultData.ErrorMessage != "") {
                        alert(resultData.ErrorMessage);
                        return;
                    } else {
                        window.location.reload();
                        return;
                    }

                }).always(function () {
                    hideLoader();
                });
            }
        }
    </script>
}

<h2>ステータス編集</h2>

<div class="form-row">
    <div class="form-group col-12 text-right">
        <button type="button" class="btn btn-primary" onclick="createData()">新規作成</button>
    </div>
</div>

<table class="table">
    <thead class=" thead-dark text-center">
        <tr>
            <th scope="col">状態名称</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.statusList.Count; i++)
        {
            if (Model.statusList[i].cd != "0")
            {
                <tr>
                    <td class="text-center">@Model.statusList[i].status</td>
                    <td class="text-right">
                        <button type="button" class="btn btn-info" onclick="editData(@Model.statusList[i].cd)">編集</button>
                        <button type="button" class="btn btn-info" onclick="delData(@Model.statusList[i].cd)">削除</button>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

<div class="text-center">
    <button type="button" class="btn btn-primary" onclick="toList()">戻る</button>
</div>

@using (Html.BeginForm("EditStatus", "Select", FormMethod.Post, new { @id = "toEditStatus" }))
{
    @Html.Hidden("statusCd", new { @id = "statusCd" })
}

@using (Html.BeginForm("CreateStatus", "Select", FormMethod.Post, new { @id = "toCreateStatus" }))
{
    @Html.Hidden("dataCd", new { @id = "dataCd" })
}

Views/Select/EditUser.cshtml
@model DBConTemplate.Models.SelectModel
@section scripts{
    @Scripts.Render("~/Scripts/DBConTemplate/EditUserData.js")
    <script type="text/javascript">
        $(function () {
            var auth = sessionStorage.getItem("auth");
            if (auth != 1) {
                window.location.href = "../Login/Login";
            }
        });

        function toList() {
            window.location.href = "../Select/EditUserList";
        }
    </script>
}

<h2>ユーザー情報更新</h2>

<table class="table">
    <thead class=" thead-dark text-center">
        <tr>
            <th scope="col">名前</th>
            <th scope="col">メールアドレス</th>
            <th scope="col">パスワード</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><input type="text" id="userName" value="@Model.userName" class="form-control"></td>
            <td><input type="text" id="mail" value="@Model.mail" class="form-control"></td>
            <td><input type="text" id="password" value="" class="form-control"></td>
        </tr>
    </tbody>
</table>

<div class="text-center">
    <button type="button" class="btn btn-primary" onclick="toList()">戻る</button>
    <button type="button" class="btn btn-primary" onclick="submitData(@Model.cd)">登録</button>
</div>

Views/Select/EditUserList.cshtml
@model DBConTemplate.Models.SelectModel
@section scripts{
    @*@Scripts.Render("~/Scripts/DBConTemplate/EditData.js")*@
    <script type="text/javascript">
        $(function () {
            var auth = sessionStorage.getItem("auth");
            if (auth != 1) {
                window.location.href = "../Login/Login";
            }
        });

        function editUserData(cd) {
            $('#userCd').val(cd);
            $('#toEditUserData').submit();
        }

        function createUser() {
            $('#toCreateUserData').submit();
        }

        function toList() {
            window.location.href = "../Select/MasterAdmin";
        }

        //データ削除処理
        function delData(cd) {
            if (!confirm("データを削除してよろしいですか？")) {
                return false;

            } else {
                $.ajax({
                    type: "POST",
                    url: "../Select/DeleteUserDataSubmit",
                    data: { cd: cd },
                    beforeSend: function () {
                        showLoader();
                    }

                }).fail(function () {
                    alert("データの取得に失敗しました。")

                }).done(function (resultData) {
                    if (resultData.ErrorMessage != null && resultData.ErrorMessage != "") {
                        alert(resultData.ErrorMessage);
                        return;
                    } else {
                        window.location.reload();
                        return;
                    }

                }).always(function () {
                    hideLoader();
                });
            }
        }
    </script>
}

<h2>ユーザー編集</h2>

<div class="form-row">
    <div class="form-group col-12 text-right">
        <button type="button" class="btn btn-primary" onclick="createUser()">新規作成</button>
    </div>
</div>

<table class="table">
    <thead class=" thead-dark text-center">
        <tr>
            <th scope="col">ユーザー名</th>
            <th scope="col">メールアドレス</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.userList.Count; i++)
        {
            if (Model.userList[i].cd != "0")
            {
                <tr>
                    <td class="text-center">@Model.userList[i].userName</td>
                    <td class="text-center">@Model.userList[i].mail</td>
                    <td class="text-right">
                        <button type="button" class="btn btn-info" onclick="editUserData(@Model.userList[i].cd)">編集</button>
                        <button type="button" class="btn btn-info" onclick="delData(@Model.userList[i].cd)">削除</button>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

<div class="text-center">
    <button type="button" class="btn btn-primary" onclick="toList()">戻る</button>
</div>

@using (Html.BeginForm("EditUser", "Select", FormMethod.Post, new { @id = "toEditUserData" }))
{
    @Html.Hidden("userCd", new { @id = "userCd" })
}

@using (Html.BeginForm("CreateUser", "Select", FormMethod.Post, new { @id = "toCreateUserData" }))
{
    @Html.Hidden("dataCd", new { @id = "dataCd" })
}

Views/Select/MasterAdmin.cshtml
@section scripts{
    <script type="text/javascript">
        $(function () {
            var auth = sessionStorage.getItem("auth");
            if (auth != 1) {
                window.location.href = "../Login/Login";
            }
        });

        function toEditUser() {
            $('#toUser').submit();
        }

        function toEditStatus() {
            $('#toData').submit();
        }
    </script>
}

<h2>マスタ管理メニュー</h2>

<div class="jumbotron">
    <div class="row main-menu">
        <div class="col-12 text-center">
            <div class="offset-4 col-4 menu-block bcg-mat" id="editUserParent" onclick="toEditUser()">
                <img src="~/Content/img/user.png" width="60" style="position:relative; top:-0.5rem; right:7rem">
                <div class="linking-title text-center" id="editUser" style="padding-bottom: 1rem; margin-top: -3.5rem; margin-left: 2rem;">
                    ユーザー編集
                </div>
                <div class="mt-1 menu-line"></div>
            </div>
            <div class="offset-4 col-4 menu-block bcg-mat mt-5" id="editUserParent" onclick="toEditStatus()">
                <img src="~/Content/img/status.png" width="60" style="position:relative; top:-0.5rem; right:7rem">
                <div class="linking-title text-center" id="editUser" style="padding-bottom: 1rem; margin-top: -3.5rem; margin-left: 2rem;">
                    ステータス編集
                </div>
                <div class="mt-1 menu-line"></div>
            </div>
        </div>
    </div>
</div>

@using (Html.BeginForm("EditUserList", "Select", FormMethod.Post, new { @id = "toUser" }))
{
    @Html.Hidden("dataCd", new { @id = "dataCd" })
}
@using (Html.BeginForm("EditStatusList", "Select", FormMethod.Post, new { @id = "toData" }))
{
    @Html.Hidden("dataCd", new { @id = "dataCd" })
}