Controllers/SelectSpController.cs
using ClosedXML.Excel;
using DBConTemplate.Models;
using MySql.Data.MySqlClient;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DBConTemplate.Controllers
{
    public class SelectSpController : Controller
    {
        //ログ
        protected static NLog.Logger log = NLog.LogManager.GetLogger("log");

        //リストページ
        public ActionResult AjaxSelectSp()
        {
            SelectModel selectModel = new SelectModel();
            String errorMessage = String.Empty;
            try
            {
                selectModel.GetStatus();
                selectModel.GetUser();
            }
            catch (Exception e)
            {
                log.Fatal(e);
                errorMessage = "データの取得に失敗しました。";
            }
            return View("AjaxSelectSp", "_LayoutMobile", selectModel);
        }

        //全件取得SP
        public ActionResult GetDataFromAjaxSp(int count, int usCd)
        {
            SelectModel selectModel = new SelectModel();
            String errorMessage = String.Empty;
            try
            {
                //データ取得
                selectModel.GetDataSp(count, usCd);
            }
            catch (Exception e)
            {
                log.Fatal(e);
                errorMessage = "データの取得に失敗しました。";
            }
            return Json(new { DATA = selectModel, ErrorMessage = errorMessage });
        }

        //降順切り替え
        public ActionResult DataSortDesc(int count)
        {
            SelectModel selectModel = new SelectModel();
            String errorMessage = String.Empty;
            try
            {
                //データ取得
                selectModel.GetDataDesc(count);
            }
            catch (Exception e)
            {
                log.Fatal(e);
                errorMessage = "データの取得に失敗しました。";
            }
            return Json(new { DATA = selectModel, ErrorMessage = errorMessage });
        }

        //昇順切り替え
        public ActionResult DataSortAsc(int count)
        {
            SelectModel selectModel = new SelectModel();
            String errorMessage = String.Empty;
            try
            {
                //データ取得
                selectModel.GetDataAsc(count);
            }
            catch (Exception e)
            {
                log.Fatal(e);
                errorMessage = "データの取得に失敗しました。";
            }
            return Json(new { DATA = selectModel, ErrorMessage = errorMessage });
        }

        //検索
        public ActionResult SearchData(string statusSearch, string chargeSearch, int count)
        {
            SelectModel selectModel = new SelectModel();
            String errorMessage = String.Empty;
            try
            {
                //データ取得
                selectModel.GetSearchData(statusSearch, chargeSearch, count);
            }
            catch (Exception e)
            {
                log.Fatal(e);
                errorMessage = "データの取得に失敗しました。";
            }
            return Json(new { DATA = selectModel, ErrorMessage = errorMessage });
        }

        //データ削除
        public ActionResult DeleteData(string cd)
        {
            SelectModel selectModel = new SelectModel();
            String errorMessage = String.Empty;
            try
            {
                selectModel.DelData(cd);
            }
            catch (Exception e)
            {
                log.Fatal(e);
                errorMessage = "データの削除に失敗しました。";
            }
            return Json(new { DATA = selectModel, ErrorMessage = errorMessage });
        }

        //新規作成画面
        public ActionResult CreateDataSp()
        {
            SelectModel selectModel = new SelectModel();
            String errorMessage = String.Empty;
            try
            {
                selectModel.GetStatus();
                selectModel.GetUser();
            }
            catch (Exception e)
            {
                log.Fatal(e);
            }
            return View("CreateDataSp", "_LayoutMobile", selectModel);
        }

        //新規作成
        public ActionResult SubmitNewData(string companyName, string companyUrl, string status, string charge, string note, string mail)
        {
            SelectModel selectModel = new SelectModel();
            String errorMessage = String.Empty;
            try
            {
                if (charge == "")
                {
                    charge = "0";
                }
                selectModel.CreateNewData(companyName, companyUrl, status, charge, note, mail);
                if (selectModel.errorFlg != 0)
                {
                    errorMessage = "データの作成に失敗しました。";
                }
            }
            catch (Exception e)
            {
                log.Fatal(e);
                errorMessage = "データの削除に失敗しました。";
            }
            return Json(new { DATA = selectModel, ErrorMessage = errorMessage });
        }

        //データ編集画面
        public ActionResult EditDataSp(string dataCd)
        {
            var SelectModel = new SelectModel();
            try
            {
                SelectModel = SelectModel.GetOneData(dataCd);
                SelectModel = SelectModel.GetStatus();
                SelectModel = SelectModel.GetUser();
            }
            catch (Exception e)
            {
                log.Fatal(e);
            }
            return View("EditDataSp", "_LayoutMobile", SelectModel);
        }

        //データ更新
        public ActionResult EditDataSubmit(string cd, string companyName, string companyUrl, string status, string charge, string note, string mail)
        {
            SelectModel selectModel = new SelectModel();
            String errorMessage = String.Empty;
            try
            {
                //データ取得
                selectModel.EditData(cd, companyName, companyUrl, status, charge, note, mail);
            }
            catch (Exception e)
            {
                log.Fatal(e);
                errorMessage = "データの削除に失敗しました。";
            }
            return Json(new { DATA = selectModel, ErrorMessage = errorMessage });
        }
    }
}

Views/SelectSp/AjaxSelectSp.cshtml
@model DBConTemplate.Models.SelectModel
@section scripts{
    @Scripts.Render("~/Scripts/DBConTemplate/AjaxSelectSp.js")
    <script type="text/javascript">
        $(function () {
            var auth = sessionStorage.getItem("auth");
            if (auth != 1) {
                window.location.href = "../Login/Login";
            }
            getData(0);
        });

        function editData(cd) {
            $('#dataCd').val(cd);
            $('#toEditData').submit();
        }
    </script>
}

<div class="row">
    <div class="col-12">
        <div class="form-row">
            <div class="form-group col-4">
                <select id="statusSearch" class="form-control">
                    <option value='' selected>状態</option>
                    @for (var i = 0; i < Model.statusList.Count; i++)
                    {
                        if (Model.statusList[i].cd != "0")
                        {
                            <option value="@Model.statusList[i].cd">@Model.statusList[i].status</option>
                        }
                    }
                </select>
            </div>
            <div class="form-group col-4">
                <select id="chargeSearch" class="form-control">
                    <option value="" selected>担当者</option>
                    @for (var i = 0; i < Model.userList.Count; i++)
                    {
                        <option value="@Model.userList[i].cd">@Model.userList[i].userName</option>
                    }
                </select>
            </div>
            <div class="form-group col-4 text-right">
                <button type="button" class="btn btn-primary" onclick="searchCheck()">検索</button>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-6 mt-1">
        <h5 id="totalCount"></h5>
    </div>
    <div class="col-6 mb-3 text-right">
        <button type="button" class="btn btn-primary " onclick="searchDataDesc(0)">↓ 降順</button>
        <button type="button" class="btn btn-primary" onclick="getData(0)">昇順 ↑</button>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <table class="table">
            <thead class="thead-dark text-center">
                <tr>
                    <th style="width: 25%">企業名</th>
                    <th style="width: 25%">担当者</th>
                    <th style="width: 25%">状態</th>
                    <th style="width: 25%"></th>
                </tr>
            </thead>
            <tbody class="text-center" id="dataList">
            </tbody>
        </table>
    </div>
</div>

<div class="row">
    <div class="col-12 text-center">
        <button type="button" class="btn btn-info" onclick="createData()">作成</button>
    </div>
</div>

<div class="row">
    <div class="col-12 text-center">
        <nav class="cp_navi" id="paging">
        </nav>
    </div>
</div>

@using (Html.BeginForm("EditDataSp", "SelectSp", FormMethod.Post, new { @id = "toEditData" }))
{
    @Html.Hidden("dataCd", new { @id = "dataCd" })
}

Views/SelectSp/CreateDataSp.cshtml
@model DBConTemplate.Models.SelectModel
@section scripts{
    @Scripts.Render("~/Scripts/DBConTemplate/CreateDataSp.js")

    <script type="text/javascript">
        $(function () {
            var auth = sessionStorage.getItem("auth");
            if (auth != 1) {
                window.location.href = "../Login/Login";
            }
        });
    </script>
}

<h2>新規作成</h2>

<table class="table table-striped">
    <tr>
        <th class="thead-dark text-center">企業名</th>
        <td class="pt-1"><span class="badge badge-danger">*</span><input type="text" id="companyName" class="form-control"></td>
    </tr>
    <tr>
        <th class="thead-dark text-center">企業URL</th>
        <td class="pt-1"><span class="badge badge-danger">*</span><input type="text" id="companyUrl" class="form-control"></td>
    </tr>
    <tr>
        <th class="text-center">状態</th>
        <td>
            <select id="status" class="form-control">
                @for (var i = 0; i < Model.statusList.Count; i++)
                {
                    if (Model.statusList[i].cd != "0")
                    {
                        <option value="@Model.statusList[i].cd">@Model.statusList[i].status</option>
                    }
                }
            </select>
        </td>
    </tr>
    <tr>
        <th class="thead-dark text-center">担当者</th>
        <td>
            <select id="charge" class="form-control">
                @for (var i = 0; i < Model.userList.Count; i++)
                {
                    if (Model.userList[i].cd == "0")
                    {
                        <option value="@Model.userList[i].cd" selected>@Model.userList[i].userName</option>
                    }
                    else
                    {
                        <option value="@Model.userList[i].cd">@Model.userList[i].userName</option>
                    }
                }
            </select>
        </td>
    </tr>
    <tr>
        <th class="text-center">備考</th>
        <td><textarea id="note" class="form-control"></textarea></td>
    </tr>
</table>

<div class="text-center">
    <button type="button" class="btn btn-primary" onclick="toList()">戻る</button>
    <button type="button" class="btn btn-primary" id="submit" onclick="submitData()">登録</button>
</div>

Views/SelectSp/CreateStatus.cshtml
@model DBConTemplate.Models.SelectModel
@section scripts{
    @Scripts.Render("~/Scripts/DBConTemplate/CreateStatus.js")

    <script type="text/javascript">
        $(function () {
            var auth = sessionStorage.getItem("auth");
            if (auth != 1) {
                window.location.href = "../Login/Login";
            }
        });
    </script>
}

<h2>ステータス新規作成</h2>

<table class="table">
    <thead class="thead-dark text-center">
        <tr>
            <th scope="col">状態名称</th>
        </tr>
    </thead>
    <tbody class="text-center">
        <tr>
            <td><input type="text" id="statusName" class="form-control"></td>
        </tr>
    </tbody>
</table>

<div class="text-center">
    <button type="button" class="btn btn-primary" onclick="toList()">戻る</button>
    <button type="button" class="btn btn-primary" id="submit" onclick="submitData()">登録</button>
</div>

Views/SelectSp/EditDataSp.cshtml
@model DBConTemplate.Models.SelectModel
@section scripts{
    @Scripts.Render("~/Scripts/DBConTemplate/EditDataSp.js")
    <script type="text/javascript">
        $(function () {
            var auth = sessionStorage.getItem("auth");
            if (auth != 1) {
                window.location.href = "../Login/Login";
            }
        });
    </script>
}

<h2>更新</h2>

<table class="table table-striped">
    <tr>
        <th class="thead-dark text-center">企業名</th>
        <td class="pt-1"><span class="badge badge-danger">*</span><input type="text" id="companyName" class="form-control" value="@Model.companyName"></td>
    </tr>
    <tr>
        <th class="thead-dark text-center">企業URL</th>
        <td class="pt-1"><span class="badge badge-danger">*</span><input type="text" id="companyUrl" class="form-control" value="@Model.companyName"></td>
    </tr>
    <tr>
        <th class="thead-dark text-center">メールアドレス</th>
        <td class="pt-1"><span class="badge badge-danger">*</span><input type="text" id="companyUrl" class="form-control" value="@Model.mail"></td>
    </tr>
    <tr>
        <th class="text-center">状態</th>
        <td>
            <select id="status" class="form-control">
                @for (var i = 0; i < Model.statusList.Count; i++)
                {
                    if (Model.statusList[i].cd != "0")
                    {
                        <option value="@Model.statusList[i].cd">@Model.statusList[i].status</option>
                    }
                }
            </select>
        </td>
    </tr>
    <tr>
        <th class="thead-dark text-center">担当者</th>
        <td>
            <select id="charge" class="form-control">
                @for (var i = 0; i < Model.userList.Count; i++)
                {
                    if (Model.userList[i].cd == "0")
                    {
                        <option value="@Model.userList[i].cd" selected>@Model.userList[i].userName</option>
                    }
                    else
                    {
                        <option value="@Model.userList[i].cd">@Model.userList[i].userName</option>
                    }
                }
            </select>
        </td>
    </tr>
    <tr>
        <th class="text-center">備考</th>
        <td><textarea id="note" class="form-control">@Model.note</textarea></td>
    </tr>
</table>

<div class="text-center">
    <button type="button" class="btn btn-primary" onclick="submitData(@Model.cd)">登録</button>
    <button type="button" class="btn btn-primary" onclick="toList()">戻る</button>
</div>